// BACKEND NOTE
// EHAT IS BACKEND?
// THIS REFERS TO THE PART OF A WEBSITE THAT OPERATES ON THE SERVER SIDE, BEHIND THE SCENES.
// ITS  IS RESPONSIBLE FOR MANAGING AND PROCESSING the data, handling business logic and performing tasks the frontend cannot handle

// USES OF BACKEND
// 1. SERVER: THE BACKEND RUNS ON A SERVER, WHICH CAN BE SINGLE COMPUTER/LAPTOP, A CLUSTER OF COMPUTERS OR SUPER COMPUTERS WHICH HOUSES THE WEBSITE/WEBAPPS
// 2. DATABASE: THE BACKEND INTERACTS WITH A DATABASE TO STORE AND RETRIEVE DATA. THIS INCLUDES USER INFORMATION, CONTENTS AND OTHER DATA NECESSARY FOR THE WEBSITE FUNCTIONALITY. (MONGODB)
// 3. SERVERSIDE PROGRAMMING LANGUAGES: JAVASCRIPT/TYPESCRIPT(NODE/{FRAMEWORK:EXPRESS}), PYTHON(DJANGO), PHP(LARAVEL)
// 4. API: (APPLICATION PROGRAMMING INTERFACE) THE BACKEND CAN EXPOSE APIS THAT THE FRONTEND USES TO REQUEST AND SEND DATA
// 5. AUTHENTICATION & AUTHORIZATION: THE BACKEND MANAGES USERS AUTHENTICATION(VERIFYING IDENTITY) AND AUTHORIZATION(GRANTING ACCESS TO RESOURCES BASED ON PERMISSION)
// 6. SECURITY: THE BACKEND IMPLEMENTS SECURITY MEASURES TO PROTECT DATA AND ENSURE THAT THE APPLICATION IS SAFE FROM VULNERABILITIES.

// TOOLS USED IN BACKEND
// VS CODE (CODE EDITOR)
// DATABASE: POSTGRES, MYSQL, MONGODB, NOSQL
// LANGUAGES: NODE....EXPRESS
// TESTERS: POSTMAN

// REQUEST & RESPONSE
// REQUEST: THERE ARE 5 TYPES OF REQUEST
// ...1. POST REQUEST: THIS INVOLVES USER SENDING THEIR INFORMATION TO A SERVER/DATABASE E.G LOGIN, SIGN-UP, INPUT E.T.C.
// ...2. GET REQUEST: RETRIEVES DATA FROM THE SERVER/DATABASE.
// ...3. DELETE REQUEST: INVOLVES LOG-OUT, DELETE ACCOUNT, DELETE A POST.
// ...4. PATCH REQUEST: THIS IS TO EDIT A DATA THAT HAS ALRAEDY BEEN HOSTED.
// ...5. PUT REQUEST: THIS IS TO UPDATE A DATA THAT HAS ALREADY BEEN HOSTED.

// RESPONSE: THERE ARE 2 TYPES
// ...1. GOOD RESPONSE
// STATUS CODE

// BACKEND FLOW
// STEP 1: APP.TS, INDEX.TS, MAIN.TS(SERVER FILES): THIS IS WHERE YOU RUN YOUR SERVER AND CONNECT TO YOUR DATA BASE
// STEP 2: YOU CREATE A MODEL FOLDER: THIS IS FOR DEFINING THE STRUCTURE OF THE DATA THAT WILL BE STORED IN YOUR DATABASE
// STEP 3: YOU CREATE THE CONTROLLER FOLDER: THIS IS WHERE THE BUSINESS LOGIC HAPPENS... WHERE YOU DEFINE WHAT HAPPENS BETWEEN REQUEST AND RESPONSE
// STEP 4: YOU CREATE THE ROUTES FOLDER: THIS IS WHERE YOU DEFINE YOUR REQUEST ROUTE
// STEP 5: YOU BRING EVERYTHING BACK TO YOUR SERVER FILE
// STEP 6: OTHER FOLDER YOU MIGHT CREATE DEPENDING OF THE SCALE OF THE PROJECT: 1. UTILS FOLDER (UTILITIES), MIDDLEWARE FOLDER ETC.

// READ ON
// CORS
// AXIOS
